version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
     # - apt-get update -y
     # - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package -Dspring.datasource.hikari.jdbc-url=$ENV:DB_URL -Dspring.datasource.hikari.username=$ENV:DB_ID -Dspring.datasource.hikari.password=$ENV:DB_PASS
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

cache:
  paths:
    - '/root/.m2/**/*'
